'use client'
import { useState, useEffect, useCallback } from 'react'
import { toast } from 'sonner'
import type { DiagramAnalysis } from '@/types/diagram'

const ZOOM_LEVELS = [50, 75, 100, 125, 150, 200]
const DEFAULT_ZOOM_IDX = 2  // 100%

interface TactileSVGProps {
  analysis: DiagramAnalysis
}

export function TactileSVG({ analysis }: TactileSVGProps) {
  const [svgString, setSvgString] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [zoomIdx, setZoomIdx] = useState(DEFAULT_ZOOM_IDX)

  useEffect(() => {
    let cancelled = false
    fetch('/api/tactile', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(analysis),
    })
      .then(async (res) => {
        if (!res.ok) {
          const data = await res.json() as { error?: string }
          throw new Error(data.error ?? `Server error ${res.status}`)
        }
        return res.text()
      })
      .then((svg) => { if (!cancelled) setSvgString(svg) })
      .catch((err) => { if (!cancelled) setError(err instanceof Error ? err.message : 'Failed to generate tactile SVG') })
    return () => { cancelled = true }
  }, [analysis])

  const zoom = ZOOM_LEVELS[zoomIdx]
  const scaledW = Math.round(794 * zoom / 100)
  const scaledH = Math.round(1123 * zoom / 100)

  const handleDownload = useCallback(() => {
    if (!svgString) return
    const blob = new Blob([svgString], { type: 'image/svg+xml' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `tactile-${analysis.title.toLowerCase().replace(/\s+/g, '-')}.svg`
    a.click()
    URL.revokeObjectURL(url)
    toast.success('Tactile SVG downloaded')
  }, [svgString, analysis.title])

  if (error) {
    return (
      <div
        style={{ background: '#18191a', border: '1px solid #23252a', borderRadius: 8, padding: '16px', fontSize: 15, color: '#8a8f98' }}
        role="alert"
      >
        Could not generate tactile SVG.
      </div>
    )
  }

  return (
    <div role="region" aria-label="Tactile braille SVG output" className="flex flex-col gap-3">
      {/* Header row: label + zoom controls */}
      <div className="flex items-center justify-between">
        <span className="text-[11px] font-medium text-[#62666d] uppercase tracking-[0.4px]">
          A4 · braille-encoded labels
        </span>

        <div
          className="flex items-center gap-1"
          style={{ background: '#141516', border: '1px solid #23252a', borderRadius: 6, padding: '3px' }}
        >
          <button
            onClick={() => setZoomIdx(i => Math.max(0, i - 1))}
            disabled={zoomIdx === 0}
            aria-label="Zoom out"
            style={{
              width: 28, height: 28, background: 'none', border: 'none', borderRadius: 4,
              color: zoomIdx === 0 ? '#3e3e44' : '#8a8f98',
              fontSize: 18, cursor: zoomIdx === 0 ? 'default' : 'pointer',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}
          >−</button>

          <span style={{ fontSize: 12, color: '#62666d', minWidth: 38, textAlign: 'center', fontVariantNumeric: 'tabular-nums' }}>
            {zoom}%
          </span>

          <button
            onClick={() => setZoomIdx(i => Math.min(ZOOM_LEVELS.length - 1, i + 1))}
            disabled={zoomIdx === ZOOM_LEVELS.length - 1}
            aria-label="Zoom in"
            style={{
              width: 28, height: 28, background: 'none', border: 'none', borderRadius: 4,
              color: zoomIdx === ZOOM_LEVELS.length - 1 ? '#3e3e44' : '#8a8f98',
              fontSize: 18, cursor: zoomIdx === ZOOM_LEVELS.length - 1 ? 'default' : 'pointer',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}
          >+</button>

          <div style={{ width: 1, height: 16, background: '#23252a', margin: '0 2px' }} />

          <button
            onClick={() => setZoomIdx(DEFAULT_ZOOM_IDX)}
            aria-label="Reset zoom to 100%"
            style={{ background: 'none', border: 'none', borderRadius: 3, fontSize: 11, fontWeight: 500, color: '#8a8f98', cursor: 'pointer', padding: '0 5px', height: 28 }}
          >Fit</button>
        </div>
      </div>

      {/* SVG viewport */}
      <div
        style={{ background: '#ffffff', border: '1px solid #34343a', borderRadius: 8, height: 380, overflow: 'auto' }}
        role="img"
        aria-label={`Tactile SVG for ${analysis.title}`}
        aria-busy={!svgString}
      >
        {svgString ? (
          <div
            style={{ width: scaledW, height: scaledH, transform: `scale(${zoom / 100})`, transformOrigin: 'top left', minWidth: scaledW, minHeight: scaledH }}
            // Safe: SVG is generated by our own server-side renderer, never from raw user input
            dangerouslySetInnerHTML={{ __html: svgString }}
          />
        ) : (
          <div className="flex items-center justify-center h-full" style={{ color: '#8a8f98', fontSize: 13 }}>
            Generating tactile SVG...
          </div>
        )}
      </div>

      {/* Print note */}
      <div style={{ background: '#18191a', border: '1px solid #23252a', borderRadius: 8, padding: '10px 14px', fontSize: 13, color: '#62666d', lineHeight: 1.6 }}>
        Optimised for swell-paper or tactile embossing printers. Print at 100% scale on A4.
      </div>

      {/* Download button */}
      <button
        onClick={handleDownload}
        disabled={!svgString}
        aria-label="Download tactile SVG for printing"
        className="w-full flex items-center justify-center gap-2 font-medium transition-colors"
        style={{
          background: svgString ? '#5e6ad2' : '#23252a',
          color: '#ffffff', borderRadius: 8, padding: '10px 16px', fontSize: 15, border: 'none',
          cursor: svgString ? 'pointer' : 'default', opacity: svgString ? 1 : 0.5,
        }}
        onMouseEnter={e => { if (svgString) (e.currentTarget as HTMLButtonElement).style.background = '#828fff' }}
        onMouseLeave={e => { if (svgString) (e.currentTarget as HTMLButtonElement).style.background = '#5e6ad2' }}
      >
        <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
          <polyline points="7,10 12,15 17,10" />
          <line x1="12" y1="15" x2="12" y2="3" />
        </svg>
        Download Tactile SVG
      </button>
    </div>
  )
}
